- src/editor.tsx
> start directly in edit mode

- server.js
- src/editor.tsx
Two changes:
* Every time the editor is opened in edusharing there shall be a new Version saved with the name `Datei wurde durch den Serlo-Editor aktualisiert`
* There shall be a button for saving a new commit version (similar to the Google docs feature `Name current version`)
> Support saving of commits

- src/pages/_app.tsx
> Include KaTeX stylesheet

- cypress.config.ts
- cypress/e2e/editor.cy.ts
- cypress/fixtures/example.json
- edusharing-server.ts
- package.json
- src/editor/editor.tsx
> Add basic cypress tests

- .prettierignore
- Dockerfile
- cypress/e2e/editor.cy.ts
- package.json
- server.ts
- tsconfig.server.json
> Move server.js to server.ts

- src/pages/platform/done.tsx
> feat: Set target orign in Deeplink done page

- __tests__/edu-sharing-deeplink-flow.ts
> test: Check that deeplink flow can only be started with ltik

- Dockerfile
> docker: Use node:16-alpine

- cypress/e2e/editor.cy.ts
> Refactor editor.cy.ts

- .env-docker
- server.ts
> fix: Proper setting of devMode for ltijs

- server.ts
- src/plugins/edusharing-asset.tsx
- src/utils/decoders.ts
> Add EdusharingAssetDecoder + rename all decoders

- .yarnrc.yml
See https://yarnpkg.com/configuration/yarnrc#supportedArchitectures
> yarn: Add config for "supportedArchitectues"

- Dockerfile
> fix: Add "public" to final docker container

- cypress/e2e/editor.cy.ts
- src/edusharing-server/server.ts
- src/pages/index.ts
- src/shared/storage-format/index.ts
Fixes #131 and includes minor ideas after refactoring #115
> test: Check that editor can be opened in view mode

- src/frontend/editor.tsx
- src/shared/storage-format/index.ts
Prevent sending a request to lti/save-content when document is null.
> 194 check that document is not null before saving it

- src/frontend/toolbar/index.tsx
> fix: Enable always "Save & close" button

- cypress/e2e/editor.cy.ts
> test: Test that no autosave is done when there are no changes

- .github/workflows/checks.yml
- .tool-versions
- Dockerfile
- package.json
- src/frontend/plugins/edusharing-asset.tsx
- yarn.lock
> chore(node): User version 18.x

- src/backend/server.ts
- src/frontend/editor.tsx
> refactor: Small changes in saving document

- src/backend/server.ts
- src/edusharing-server/server.ts
- src/server-utils.ts
> refactor: Small changes in deeplink

- src/frontend/plugins/serlo-injection/index.ts
- src/frontend/save-version-modal.tsx
~can't test right now but this should do the trick 🙃~
Borrowed from frontend code.
> fix modal zIndex problem

- .github/workflows/docker.yml
- src/frontend/plugins/index.tsx
- src/frontend/plugins/registry.ts
Anchor plugin will be removed soon from `frontend` and replaced by something else.
> feat!: Remove anchor plugin

- package.json
See https://github.com/serlo/db-migrations/pull/85#discussion_r1270893376 by @eliflores
> chore: Update "yarn docker:build"

- src/frontend/plugins/edusharing-asset.tsx
> feat: Add buttons to change the size of edu-sharing assets

- .eslintrc.json
- package.json
- src/frontend/plugins/create-plugins.tsx
- src/frontend/plugins/create-renderers.tsx
**Fix**: Disallow creating geogebra and exercise plugins as child within other plugins.
> Version 1.3.1

- package.json
See https://github.com/TypeStrong/ts-node/issues/2094
> chore: Fix call of ts-node

- .tool-versions
So we match to the pinned version in all other repos
> chore: Change pinned Node version

- src/backend/server.ts
edu-sharing suggested this change to hopefully fix the character encoding issue.
> Use display mode embed to hopefully fix character encoding issue

- src/frontend/plugins/create-plugins.tsx
- src/frontend/plugins/create-renderers.tsx
- tsconfig.json
> Fix geogebra

- package.json
- Fix: Video embed
- Feat: Geogebra plugin available again
> Version 1.6.0

- src/frontend/editor.tsx
- src/frontend/layout.tsx
> fix(visual): Decrease vertical spacing at the top in learner view

- package.json
- https://github.com/serlo/serlo-editor-for-edusharing/pull/323
- https://github.com/serlo/serlo-editor-for-edusharing/pull/322
> fix: Version 1.6.1

- src/frontend/plugins/create-plugins.tsx
- src/frontend/plugins/create-renderers.tsx
- src/shared/storage-format/index.ts
- src/shared/storage-format/kitchen-sink.ts
Existing content will still work but newly created content will be wrapped in `type-generic-content`. -> No breaking change.
> feat(content-format): Use `type-generic-content` as wrapper for all newly created content

- package.json
- https://github.com/serlo/serlo-editor-for-edusharing/pull/330
- https://github.com/serlo/serlo-editor-for-edusharing/pull/329
- https://github.com/serlo/serlo-editor-for-edusharing/pull/327
- https://github.com/serlo/serlo-editor-for-edusharing/pull/325
> Version 1.7.0

- __tests__/editor.ts
- package.json
- src/backend/server.ts
- feat(mongodb): Rename mongodb collection to avoid clash with existing collection
> Version 1.8.0

- Dockerfile
- next.config.mjs
- scripts/esbuild.js
- src/backend/server.ts
Before: Nextjs custom server was initialized with empty config. Although this did not lead to any errors, it might lead to errors in the future.  
After: Uses config defined in `next.config.mjs`.
> fix(next-custom-server): Apply next config when using custom server

- package.json
- https://github.com/serlo/serlo-editor-for-edusharing/pull/361
- https://github.com/serlo/serlo-editor-for-edusharing/pull/362
> Version 2.3.0

- package.json
Changelog: 
- #368
- #363
- #366
- #365
- Spoiler element can now have formatting & math & code in header
> Version 2.4.0
